FROM node:22-bookworm-slim
WORKDIR /app
COPY package.json package-lock.json .npmrc ./
RUN npm ci
COPY packages/database ./packages/database
RUN npm run db:generate
COPY . .
USER node
EXPOSE 4320
CMD ["npm", "start"]
