import {existsSync} from 'node:fs';
if(existsSync(new URL('./collection.lock.json',import.meta.url)))throw new Error('COLLECTION LOCKED: approved artwork and assignments cannot be overwritten. Create a separate edition for further experiments.');
import {mkdirSync,writeFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {catalog,select} from './config';import {renderEntity} from './renderer';import {writePng} from './png.mjs';
mkdirSync('public/metadata',{recursive:true});const items=[],seen=new Set(),hashes=new Set();let seed=1;
while(items.length<888){const selected=select(seed);const sig=JSON.stringify(selected);if(seen.has(sig)){seed++;continue}seen.add(sig);const id=items.length+1;const {buf,W,H}=renderEntity(seed,selected,480);const hash=createHash('sha256').update(buf).digest('hex');if(hashes.has(hash))throw Error('Duplicate artwork');hashes.add(hash);writePng(`public/art/${id}.png`,Buffer.from(buf),W,H);items.push({id,seed,selected,image:`art/${id}.png?v=3`,hash});seed++;if(id%100===0)console.log(`Rendered ${id}/888`)}
const counts={};for(const d of catalog){counts[d.key]={};for(const c of d.choices)counts[d.key][c.id]=items.filter(i=>i.selected[d.key]===c.id).length}
for(const item of items){item.score=Number(catalog.reduce((a,d)=>a+888/counts[d.key][item.selected[d.key]],0).toFixed(4));item.attributes=catalog.map(d=>{const c=d.choices.find(c=>c.id===item.selected[d.key]);return {trait_type:d.label,value:c.label,count:counts[d.key][c.id],percent:Number((counts[d.key][c.id]/888*100).toFixed(2)),designTier:c.tier}})}
[...items].sort((a,b)=>b.score-a.score||a.id-b.id).forEach((i,n)=>i.rank=n+1);
for(const item of items)writeFileSync(`public/metadata/${item.id}.json`,JSON.stringify({name:`hive.md Agent #${String(item.id).padStart(3,'0')}`,description:'Face-only generative identity for an existing AI agent on Solana.',image:`../art/${item.id}.png`,attributes:item.attributes.map(({trait_type,value})=>({trait_type,value})),properties:{seed:item.seed,artHash:item.hash}},null,2));
const possible=catalog.reduce((a,d)=>a*d.choices.length,1);writeFileSync('public/collection.json',JSON.stringify({supply:888,possible,catalog,counts,items,validation:{uniqueTraitCombinations:seen.size,uniqueImages:hashes.size},rarityMethod:'Sum of 888 / trait count across seven visual categories. Higher score is rarer. Ties ordered by token ID. Design tiers describe generation weights, not collection rank.'}));console.log(JSON.stringify({supply:items.length,possible,uniqueImages:hashes.size,uniqueTraits:seen.size}));
