import {renderEntity} from './renderer';
const $=s=>document.querySelector(s);let data,page=0,filtered=[],activeId=1,comboPage=0,labTimer;const pageSize=40,comboSize=50;const filters={};const format=n=>n.toLocaleString();const pad=n=>String(n).padStart(3,'0');
function view(name){for(const id of ['gallery','traits','lab','combinations'])$('#'+id).hidden=id!==name;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===name)));if(name==='lab')renderLab();if(name==='combinations')renderCombos();}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));
function options(d,all=false){return (all?'<option value="">All '+d.label.toLowerCase()+'</option>':'')+d.choices.map(c=>`<option value="${c.id}">${c.label}${all?' ('+data.counts[d.key][c.id]+')':''}</option>`).join('')}
function setup(){ $('#possible').textContent=format(data.possible);$('#validation').textContent=`[ ${data.validation.uniqueImages} UNIQUE IMAGES / ${data.validation.uniqueTraitCombinations} UNIQUE TRAIT SETS ]`;$('#rarity-method').textContent=data.rarityMethod;$('#filters').innerHTML=data.catalog.map(d=>`<label>${d.label.toUpperCase()}<select data-filter="${d.key}">${options(d,true)}</select></label>`).join('');document.querySelectorAll('[data-filter]').forEach(e=>e.onchange=()=>{filters[e.dataset.filter]=e.value;page=0;renderGallery()});$('#lab-fields').innerHTML=data.catalog.map(d=>`<label>${d.label.toUpperCase()}<select data-lab="${d.key}">${options(d)}</select></label>`).join('');document.querySelectorAll('[data-lab]').forEach(e=>e.onchange=scheduleLab);$('#lab-seed').oninput=scheduleLab;$('#combo-jump').max=data.possible;$('#combo-count').textContent=`${format(data.possible)} combinations / 888 selected`;$('#combo-head').innerHTML='<tr><th>INDEX</th>'+data.catalog.map(d=>`<th>${d.label.toUpperCase()}</th>`).join('')+'<th></th></tr>';renderTraits();renderGallery();setLab(data.items[45]);$('#loading').hidden=true;view('gallery');}
function renderGallery(){const q=$('#search').value.trim().toLowerCase().replace(/^#/,'');filtered=data.items.filter(i=>data.catalog.every(d=>!filters[d.key]||i.selected[d.key]===filters[d.key])&&(!q||(/^\d+$/.test(q)?i.id===Number(q):i.attributes.some(a=>a.value.toLowerCase().includes(q)))));const sort=$('#sort').value;filtered.sort((a,b)=>sort==='rare'?a.rank-b.rank:sort==='common'?b.rank-a.rank:a.id-b.id);const pages=Math.max(1,Math.ceil(filtered.length/pageSize));page=Math.min(page,pages-1);$('#result-count').textContent=`${filtered.length} / 888 IDENTITIES`;$('#grid').innerHTML=filtered.slice(page*pageSize,(page+1)*pageSize).map(i=>`<button class="nft" data-id="${i.id}" aria-label="Inspect hive.md Agent ${pad(i.id)}, rarity rank ${i.rank}"><img src="${i.image}" alt="${i.attributes[4].value} ${i.attributes[0].value} face on ${i.attributes[5].value}" loading="lazy" width="480" height="480"><div class="card-meta"><span>hive.md / ${pad(i.id)}</span><span class="rank">RANK #${i.rank}</span></div><div class="card-bottom">${i.attributes[4].value.toUpperCase()} / ${i.attributes[5].value.toUpperCase()}</div></button>`).join('')||'<div class="empty">[ NO MATCHING IDENTITIES ]<br>Try clearing a filter or searching another trait.</div>';document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openDetail(Number(b.dataset.id)));$('#page-label').textContent=`PAGE ${page+1} / ${pages}`;$('#prev').disabled=page===0;$('#next').disabled=page>=pages-1;}
$('#search').oninput=()=>{page=0;renderGallery()};$('#sort').onchange=()=>{page=0;renderGallery()};$('#reset').onclick=()=>{for(const k in filters)delete filters[k];document.querySelectorAll('[data-filter]').forEach(e=>e.value='');$('#search').value='';$('#sort').value='id';page=0;renderGallery()};$('#prev').onclick=()=>{page--;renderGallery();$('#grid').scrollIntoView({block:'start'})};$('#next').onclick=()=>{page++;renderGallery();$('#grid').scrollIntoView({block:'start'})};
function openDetail(id){activeId=id;const i=data.items[id-1];$('#detail-title').textContent=`hive.md / AGENT ${pad(id)}`;$('#detail-image').src=i.image;$('#detail-image').alt=`Agent ${id}: ${i.attributes.map(a=>a.value).join(', ')}`;$('#detail-summary').innerHTML=`<span>RANK <b>#${i.rank} / 888</b></span><span>SCORE ${i.score.toFixed(2)}</span>`;$('#detail-traits').innerHTML=i.attributes.map(a=>`<div class="detail-attribute"><div>${a.value}<span>${a.trait_type.toUpperCase()} / ${a.designTier.toUpperCase()}</span></div><div>${a.percent}%<span>${a.count} OF 888</span></div></div>`).join('');$('#download-art').href=i.image;$('#download-art').download=`hive-${pad(id)}.png`;$('#download-meta').href=`metadata/${id}.json`;$('#download-meta').download=`hive-${pad(id)}.json`;$('#detail-seed').textContent=`SEED ${i.seed} / SHA256 ${i.hash}`;$('#detail-prev').disabled=id===1;$('#detail-next').disabled=id===888;if(!$('#detail').open)$('#detail').showModal();}
$('#close').onclick=()=>$('#detail').close();$('#detail-prev').onclick=()=>openDetail(activeId-1);$('#detail-next').onclick=()=>openDetail(activeId+1);$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});$('#open-lab').onclick=()=>{setLab(data.items[activeId-1]);$('#detail').close();view('lab')};
function renderTraits(){$('#trait-tables').innerHTML=data.catalog.map(d=>`<article class="trait-panel"><h3>${d.label} / ${d.choices.length}</h3>${d.choices.map(c=>{const n=data.counts[d.key][c.id],percent=n/888*100;return `<button class="trait-row" data-category="${d.key}" data-choice="${c.id}"><div class="trait-name"><span>${c.rgb?`<i class="swatch" style="background:rgb(${c.rgb.map(v=>Math.round(v*255)).join(',')})"></i>`:''}${c.label}</span><span>${percent.toFixed(2)}%</span></div><div class="trait-sub"><span>${c.tier.toUpperCase()} / WEIGHT ${c.weight}</span><span>${n} / 888</span></div><div class="meter"><i style="width:${percent}%"></i></div></button>`}).join('')}</article>`).join('');document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{$('#reset').click();filters[b.dataset.category]=b.dataset.choice;$(`[data-filter="${b.dataset.category}"]`).value=b.dataset.choice;renderGallery();view('gallery')})}
function setLab(item){for(const [k,v] of Object.entries(item.selected))$(`[data-lab="${k}"]`).value=v;$('#lab-seed').value=item.seed;}
function scheduleLab(){clearTimeout(labTimer);labTimer=setTimeout(renderLab,120)}
function renderLab(){const seed=Number($('#lab-seed').value);if(!Number.isInteger(seed)||seed<1||seed>999999){$('#lab-status').textContent='Enter a whole-number seed from 1 to 999,999.';$('#save-png').disabled=true;return}const selected=Object.fromEntries([...document.querySelectorAll('[data-lab]')].map(e=>[e.dataset.lab,e.value]));const {buf,W,H}=renderEntity(seed,selected,480);const ctx=$('#lab-canvas').getContext('2d');const image=ctx.createImageData(W,H);for(let i=0,j=0;i<buf.length;i+=3,j+=4){image.data[j]=buf[i];image.data[j+1]=buf[i+1];image.data[j+2]=buf[i+2];image.data[j+3]=255}ctx.putImageData(image,0,0);const match=data.items.find(i=>data.catalog.every(d=>i.selected[d.key]===selected[d.key]));$('#lab-status').textContent=match?`TRAIT SET MATCH / AGENT ${pad(match.id)} / COLLECTION SEED ${match.seed}`:'CUSTOM COMBINATION / OUTSIDE THE 888-PIECE COLLECTION';$('#save-png').disabled=false;}
$('#randomize').onclick=()=>{document.querySelectorAll('[data-lab]').forEach(e=>e.selectedIndex=Math.floor(Math.random()*e.options.length));$('#lab-seed').value=Math.floor(Math.random()*999999)+1;renderLab()};$('#save-png').onclick=()=>{$('#lab-canvas').toBlob(blob=>{const a=document.createElement('a');const url=URL.createObjectURL(blob);a.href=url;a.download=`hive-lab-${$('#lab-seed').value}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)})};
function combination(n){const selected={};for(let i=data.catalog.length-1;i>=0;i--){const d=data.catalog[i];selected[d.key]=d.choices[n%d.choices.length].id;n=Math.floor(n/d.choices.length)}return selected;}
function renderCombos(){const start=comboPage*comboSize,end=Math.min(data.possible,start+comboSize);let html='';for(let n=start;n<end;n++){const selected=combination(n);html+=`<tr><td>${format(n+1)}</td>`+data.catalog.map(d=>`<td>${d.choices.find(c=>c.id===selected[d.key]).label}</td>`).join('')+`<td><button data-combo="${n}">INSPECT ↗</button></td></tr>`}$('#combo-body').innerHTML=html;$('#combo-page').textContent=`${format(start+1)}–${format(end)} / ${format(data.possible)}`;$('#combo-prev').disabled=comboPage===0;$('#combo-next').disabled=end>=data.possible;document.querySelectorAll('[data-combo]').forEach(b=>b.onclick=()=>{setLab({seed:46,selected:combination(Number(b.dataset.combo))});view('lab')})}
$('#combo-prev').onclick=()=>{comboPage--;renderCombos()};$('#combo-next').onclick=()=>{comboPage++;renderCombos()};$('#jump').onclick=()=>{const n=Number($('#combo-jump').value);if(!Number.isInteger(n)||n<1||n>data.possible){$('#combo-jump').setCustomValidity(`Enter 1 to ${data.possible}.`);$('#combo-jump').reportValidity();return}$('#combo-jump').setCustomValidity('');comboPage=Math.floor((n-1)/comboSize);renderCombos()};$('#combo-jump').oninput=()=>$('#combo-jump').setCustomValidity('');
fetch('collection.json?v=locked').then(r=>{if(!r.ok)throw Error('Collection missing');return r.json()}).then(d=>{data=d;setup()}).catch(e=>{$('#loading').textContent='Unable to load collection. Refresh to retry.';console.error(e)});
